[uwsgi]

wsgi-file = main.py
callable = app
socket = :8080
processes = 4
threads = 2
master = true
chmod-socket = 660
vacuum = true
die-on-term = true

py-autoreload = 1

uid = www-data 
gid = www-data 

# socket文件，配置nginx时候使用
# socket=/tmp/uwsgi.sock 
# chmod-socket=666
#logfile-chown = root:root
# logfile-chmod=666
# status文件，可以查看uwsgi的執行狀態
# stats=/tmp/uwsgi.status 
# pid文件，透過該文件可以控制uwsgi的重起和停止
# pidfile=/tmp/uwsgi.pid 
# 設置後端程序紀錄模式，將紀錄輸出至uwsgi.log，可在每一次啟動uwsgi前，先清除內容，不然日誌紀錄會一直延伸下去
# daemonize=%(chdir)/uwsgi/uwsgi.log 